In [187]:
'''
Red is solid, green is dashed
Lines touching form a loop
If differenct colour line touch, seperate
Begins on first tile and ends up on first tile
'''
import numpy as np

square_points = [[[1,0],[1,2]],
         [[0,1],[2,1]],
         [[1,0],[0,1]],
         [[0,1],[1,2]],
         [[2,1],[1,2]],
         [[1,0],[2,1]]]
    
squares = []
for points in square_points:
    square = np.zeros((3,3))
    for point in points:
        square[point[0]][point[1]] = 1
    squares.append(square)
    
def adjacent_points(point):
    x,y = point
    return [[x-1,y],
            [x,y+1],
            [x+1,y],
            [x,y-1],]
    
class Grid():
    def __init__(self,n):
        self.grid = np.zeros((3*n,3*n))
        self.square_indices = []
        for i in range(n):
            for x in range(n):
                square = []
                for a in range(3):
                    for b in range(3):
                        square.append([i*3+a,x*3+b])
                self.square_indices.append(square)
        self.indices = []
        for a in range(3*n):
            for b in range(3*n):
                self.indices.append([a,b])
        self.connections = []
                
    def place_square(self,square_index,square_position):
        values = squares[square_index].flatten()
        indices = self.square_indices[square_position]
        for i in range(len(indices)):
            #print(indices[i],values[i])
            self.grid[indices[i][0]][indices[i][1]] = values[i]
            
    def which_square(self,point):
        counter = 0
        for square in self.square_indices:
            if list(point) in square:
                return counter
            counter += 1
    
    def check_connections(self):
        vertices = np.transpose(np.where(grid.grid == 1))
        for vertex in vertices:
            points = adjacent_points(vertex)
            square_1 = self.which_square(vertex)
            for point in points:
                if point in self.indices:
                    if self.grid[point[0]][point[1]] == 1:
                        square_2 = self.which_square(point)
                        self.connections.append([square_1,square_2])
                        
                        
    def find_shapes(self):
        filled_squares = np.unique(self.connections)
        def continue_path(base_point,square,path):
            possible_points = [point[1] for point in self.connections if point[0] == square]
            print("GAY",base_point,path,square,possible_points)
            for point in possible_points:
                if point == base_point and len(path) >= 4:
                    path.append(point)
                    print("OH YEAH YEAH",path)
                    return path,True
                if not(point in path):
                    new_path = path[:]
                    new_path.append(point)
                    continue_path(base_point,point,new_path)
        for square in filled_squares:
            print(square)
            print(continue_path(square,square,[square]))
            
        
    

In [188]:
grid = Grid(2)
grid.place_square(4,0)
grid.place_square(5,1)
grid.place_square(3,2)
grid.place_square(2,3)
print(grid.grid)
grid.check_connections()
print(grid.connections)
grid.find_shapes()

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0, 1], [1, 0], [0, 2], [1, 3], [2, 0], [3, 1], [2, 3], [3, 2]]
0
GAY 0 [0] 0 [1, 2]
GAY 0 [0, 1] 1 [0, 3]
GAY 0 [0, 1, 3] 3 [1, 2]
GAY 0 [0, 1, 3, 2] 2 [0, 3]
OH YEAH YEAH [0, 1, 3, 2, 0]
GAY 0 [0, 2] 2 [0, 3]
GAY 0 [0, 2, 3] 3 [1, 2]
GAY 0 [0, 2, 3, 1] 1 [0, 3]
OH YEAH YEAH [0, 2, 3, 1, 0]
None
1
GAY 1 [1] 1 [0, 3]
GAY 1 [1, 0] 0 [1, 2]
GAY 1 [1, 0, 2] 2 [0, 3]
GAY 1 [1, 0, 2, 3] 3 [1, 2]
OH YEAH YEAH [1, 0, 2, 3, 1]
GAY 1 [1, 3] 3 [1, 2]
GAY 1 [1, 3, 2] 2 [0, 3]
GAY 1 [1, 3, 2, 0] 0 [1, 2]
OH YEAH YEAH [1, 3, 2, 0, 1]
None
2
GAY 2 [2] 2 [0, 3]
GAY 2 [2, 0] 0 [1, 2]
GAY 2 [2, 0, 1] 1 [0, 3]
GAY 2 [2, 0, 1, 3] 3 [1, 2]
OH YEAH YEAH [2, 0, 1, 3, 2]
GAY 2 [2, 3] 3 [1, 2]
GAY 2 [2, 3, 1] 1 [0, 3]
GAY 2 [2, 3, 1, 0] 0 [1, 2]
OH YEAH YEAH [2, 3, 1, 0, 2]
None
3
GAY 3 [3] 3 [1, 2]
GAY 3 [3, 1] 1 [0, 3]
GAY 3 [3, 1, 0] 0 [1, 2]
GAY 3 [3, 1, 0, 2] 2 [0, 3]
OH YEAH YE

In [129]:
grid.check_connections()

In [130]:
grid.connections

[[0, 1], [1, 0]]

In [118]:
n = 2
for a in range(3*n):
    for b in range(3*n):
        print([a,b])

[0, 0]
[0, 1]
[0, 2]
[0, 3]
[0, 4]
[0, 5]
[1, 0]
[1, 1]
[1, 2]
[1, 3]
[1, 4]
[1, 5]
[2, 0]
[2, 1]
[2, 2]
[2, 3]
[2, 4]
[2, 5]
[3, 0]
[3, 1]
[3, 2]
[3, 3]
[3, 4]
[3, 5]
[4, 0]
[4, 1]
[4, 2]
[4, 3]
[4, 4]
[4, 5]
[5, 0]
[5, 1]
[5, 2]
[5, 3]
[5, 4]
[5, 5]


In [106]:
np.transpose(np.where(grid.grid == 1))

array([[1, 0],
       [1, 2],
       [1, 3],
       [1, 5]], dtype=int64)

In [ ]:
grid.

In [38]:
square_points = [[[1,0],[1,2]],
         [[0,1],[2,1]],
         [[1,0],[0,1]],
         [[0,1],[1,2]],
         [[2,1],[1,2]],
         [[1,0],[2,1]]]

squares = []
for points in square_points:
    square = np.zeros((3,3))
    for point in points:
        square[point[0]][point[1]] = 1
    squares.append(square) 

In [39]:
squares

[array([[0., 0., 0.],
        [1., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 1., 0.],
        [0., 0., 0.],
        [0., 1., 0.]]),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]])]

In [5]:
connect_pairs = np.array([[[1,2],[1,0]],
                 [[2,1],[0,1]],
                 [[1,2],[2,1]],
                 [[1,0],[2,1]],
                 [[0,1],[1,0]],
                 [[0,1],[1,2]]])

array([[[1, 2, 1, 1, 0, 0],
        [1, 0, 2, 2, 1, 1]],

       [[2, 1, 2, 0, 1, 1],
        [0, 1, 1, 1, 0, 2]]])

In [50]:
square_points = []
n = 4
for i in range(n):
    for x in range(n):
        square = []
        for a in range(3):
            for b in range(3):
                square.append([i*3+a,x*3+b])
        square_points.append(square)

In [51]:
square_points

[[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]],
 [[0, 3], [0, 4], [0, 5], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5]],
 [[0, 6], [0, 7], [0, 8], [1, 6], [1, 7], [1, 8], [2, 6], [2, 7], [2, 8]],
 [[0, 9],
  [0, 10],
  [0, 11],
  [1, 9],
  [1, 10],
  [1, 11],
  [2, 9],
  [2, 10],
  [2, 11]],
 [[3, 0], [3, 1], [3, 2], [4, 0], [4, 1], [4, 2], [5, 0], [5, 1], [5, 2]],
 [[3, 3], [3, 4], [3, 5], [4, 3], [4, 4], [4, 5], [5, 3], [5, 4], [5, 5]],
 [[3, 6], [3, 7], [3, 8], [4, 6], [4, 7], [4, 8], [5, 6], [5, 7], [5, 8]],
 [[3, 9],
  [3, 10],
  [3, 11],
  [4, 9],
  [4, 10],
  [4, 11],
  [5, 9],
  [5, 10],
  [5, 11]],
 [[6, 0], [6, 1], [6, 2], [7, 0], [7, 1], [7, 2], [8, 0], [8, 1], [8, 2]],
 [[6, 3], [6, 4], [6, 5], [7, 3], [7, 4], [7, 5], [8, 3], [8, 4], [8, 5]],
 [[6, 6], [6, 7], [6, 8], [7, 6], [7, 7], [7, 8], [8, 6], [8, 7], [8, 8]],
 [[6, 9],
  [6, 10],
  [6, 11],
  [7, 9],
  [7, 10],
  [7, 11],
  [8, 9],
  [8, 10],
  [8, 11]],
 [[9, 0],
  [9, 1],
  [9, 2],
  [1

In [33]:
square_starts

[[0, 0],
 [0, 3],
 [0, 6],
 [0, 9],
 [3, 0],
 [3, 3],
 [3, 6],
 [3, 9],
 [6, 0],
 [6, 3],
 [6, 6],
 [6, 9],
 [9, 0],
 [9, 3],
 [9, 6],
 [9, 9]]