In [171]:
'''
Infinite squares
- 4 or more people, each move to adjacent square
- Each step, a new person is added
- Keep moving until no overcrowded
- People spawned in the 5*5 square and nowhere else
- starting position and added modifiers 
'''
import numpy as np

def adjacent_squares(coord):
    x = coord[0]
    y = coord[1]
    return [[x-1,y],
            [x,y+1],
            [x+1,y],
            [x,y-1]]


class Landscape():
    def __init__(self,position,modifiers,steps):
        self.position = position
        self.steps = steps
        self.modifiers = modifiers
        self.grid = np.zeros((15,15))
        self.indices = []
        for a in range(15):
            for b in range(15):
                self.indices.append([a,b])
                
        self.five_by_five = []
        for a in range(5):
            for b in range(5):
                self.five_by_five.append(np.array([a,b]) + [4,4])
                
    def update(self):
        while True:
            overcrowded = np.transpose(np.where(self.grid == 4))
            if not(list(overcrowded)):
                break
            print(overcrowded)
            for point in list(overcrowded):
                self.grid[point[0]][point[1]] = 0
                print(point)
                adjacent_points = adjacent_squares(point)
                for point in adjacent_points:
                    if list(point) in list(self.indices):
                        print("YO")
                        self.grid[point[0]][point[1]] += 1
                    
    def add_people(self):
        place_coord = self.five_by_five[self.position-1]
        self.grid[place_coord[0]][place_coord[1]] += 1
        print(self.position)
        self.position += self.modifiers[0]
        if self.position > 25:
            self.position -= 25
        self.modifiers.append(self.modifiers[0])
        self.modifiers.pop(0)
    
    def execute(self):
        for i in range(self.steps):
            self.add_people()
            #print(landscape.grid)
            #print()
            self.update()
            #print(landscape.grid)
            #print("DASDF")
            
    def print_grid(self):
        five_by_five = np.array(self.five_by_five).reshape(5,5,2)

        for row in five_by_five:
            row_string = ''
            for value in row:
                row_string += str(int(self.grid[value[0]][value[1]]))
                row_string += ' '
            print(row_string)

In [203]:
landscape = Landscape(3,[2,3,5,7,11,13],150)
landscape.execute()
landscape.print_grid()

3
5
8
13
20
6
19
21
24
4
11
22
10
12
15
20
2
13
1
3
6
11
18
4
17
19
22
2
9
20
8
10
13
18
25
11
24
1
4
9
16
2
15
17
20
[[7 8]]
[7 8]
YO
YO
YO
YO
25
7
18
6
8
11
[[6 4]]
[6 4]
YO
YO
YO
YO
[[5 4]]
[5 4]
YO
YO
YO
YO
16
23
9
22
24
2
[[4 5]]
[4 5]
YO
YO
YO
YO
[[4 4]]
[4 4]
YO
YO
YO
YO
7
[[5 5]]
[5 5]
YO
YO
YO
YO
[[5 6]]
[5 6]
YO
YO
YO
YO
[[4 6]
 [5 7]
 [6 6]]
[4 6]
YO
YO
YO
YO
[5 7]
YO
YO
YO
YO
[6 6]
YO
YO
YO
YO
[[6 5]
 [7 6]]
[6 5]
YO
YO
YO
YO
[7 6]
YO
YO
YO
YO
[[7 5]
 [7 7]]
[7 5]
YO
YO
YO
YO
[7 7]
YO
YO
YO
YO
[[7 4]
 [8 5]
 [8 7]]
[7 4]
YO
YO
YO
YO
[8 5]
YO
YO
YO
YO
[8 7]
YO
YO
YO
YO
[[8 6]
 [8 8]]
[8 6]
YO
YO
YO
YO
[8 8]
YO
YO
YO
YO
14
[[6 7]]
[6 7]
YO
YO
YO
YO
[[6 8]]
[6 8]
YO
YO
YO
YO
[[5 8]]
[5 8]
YO
YO
YO
YO
25
13
[[6 6]]
[6 6]
YO
YO
YO
YO
[[5 6]
 [7 6]]
[5 6]
YO
YO
YO
YO
[7 6]
YO
YO
YO
YO
15
18
23
5
16
4
6
9
[[5 7]]
[5 7]
YO
YO
YO
YO
14
[[6 7]]
[6 7]
YO
YO
YO
YO
[[7 7]]
[7 7]
YO
YO
YO
YO
[[7 8]]
[7 8]
YO
YO
YO
YO
[[6 8]]
[6 8]
YO
YO
YO
YO
21
[[8 4]]
[8 4]
YO
YO
YO
YO
7
[[5 5]]
[5 5]


In [135]:
five_by_five = []
for a in range(5):
    for b in range(5):
        five_by_five.append(list(np.array([a,b]) + [4,4]))

In [146]:
five_by_five = np.array(five_by_five).reshape(5,5,2)

for row in five_by_five:
    row_string = ''
    for value in row:
        row_string += str(int(landscape.grid[value[0]][value[1]]))
        row_string += ' '
    print(row_string)

0 0 1 0 0 
0 1 2 1 0 
0 0 1 0 0 
0 0 0 0 0 
0 0 0 0 0 


In [30]:
indices = []
for a in range(5):
    for b in range(5):
        indices.append(np.array([a,b]) + [4,4])
len(indices)

25

In [32]:
indices[24]

array([8, 8])

In [4]:
import numpy as np
a = np.zeros((10,10))

In [16]:
if list(np.transpose(np.where(a == 0))):
    print("Y^W")

Y^W


In [79]:
a = [0,1,2,3]
a.append(0)
a.pop(0)

0

In [83]:
a

[1, 2, 3, 0]

In [84]:
''.join(a)

TypeError: sequence item 0: expected str instance, int found

In [85]:
''.join(['A','B','C'])

'ABC'